"""
parking_upgrade.py
Upgraded Smart Parking Management System (single-file)
Features:
 - Tkinter GUI (ttk) with multiple screens
 - SQLite database with 4 tables: users, vehicles, slots, payments
 - Password hashing with hashlib.sha256
 - CRUD operations for users, vehicles, slots
 - Slot management, billing, payments and receipts
 - User profile management
 - Admin role + admin management screens
 - Receipt export (text file) and recorded in DB
 - Simple toast notifications and robust validations
"""

import tkinter as tk
from tkinter import ttk, messagebox, simpledialog, filedialog
import sqlite3
import datetime
import hashlib
import os
import sys
import math
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure

# ----------------- CONFIG -----------------
APP_TITLE = "Smart Parking Management System (Upgraded)"
DB_FILE = "parking_system_upgraded.db"
WINDOW_SIZE = "1100x700"
CURRENCY = "UGX"
HOURLY_RATE_CAR = 1000      # Example: 1000 UGX per hour
HOURLY_RATE_MOTOR = 500     # Example: 500 UGX per hour

# Email settings (can be configured via Settings page)
EMAIL_SETTINGS = {
    'smtp_server': 'smtp.gmail.com',
    'smtp_port': 587,
    'sender_email': '',
    'sender_password': '',
    'enabled': False
}

# ----------------- STYLES / COLORS -----------------
BG = "#f4f6f8"
CARD = "#ffffff"
ACCENT = "#1e88e5"
SUCCESS = "#22c55e"
ERROR = "#ef4444"
TEXT = "#111827"

# ----------------- UTILITIES -----------------
def hash_password(password: str) -> str:
    """Return SHA-256 hash of the provided password string."""
    return hashlib.sha256(password.encode("utf-8")).hexdigest()

def now_str() -> str:
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def hours_between(start_iso: str, end_iso: str) -> float:
    """Return hours (float) between two ISO-like time strings."""
    fmt = "%Y-%m-%d %H:%M:%S"
    a = datetime.datetime.strptime(start_iso, fmt)
    b = datetime.datetime.strptime(end_iso, fmt)
    delta = b - a
    return delta.total_seconds() / 3600.0

# ----------------- PDF GENERATION -----------------
def generate_pdf_receipt(vehicle_data, amount, duration_hours, payment_method, generated_by, filepath):
    """Generate a PDF receipt for a vehicle payment"""
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title = Paragraph("<b>SMART PARKING RECEIPT</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 0.3*inch))
    
    # Receipt details
    data = [
        ['Generated:', now_str()],
        ['Vehicle Number:', vehicle_data[1]],
        ['Vehicle Type:', vehicle_data[2]],
        ['Parked By:', vehicle_data[3]],
        ['Entry Time:', vehicle_data[5]],
        ['Exit Time:', vehicle_data[6]],
        ['Duration (hours):', f"{duration_hours:.2f}"],
        ['Amount:', f"{amount:.2f} {CURRENCY}"],
        ['Payment Method:', payment_method.upper()],
        ['Generated By:', generated_by],
    ]
    
    table = Table(data, colWidths=[2*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 0.5*inch))
    
    # Footer
    footer = Paragraph("<i>Thank you for using our parking service!</i>", styles['Normal'])
    elements.append(footer)
    
    doc.build(elements)
    return filepath

def send_email_with_attachment(recipient, subject, body, attachment_path=None):
    """Send email with optional PDF attachment"""
    if not EMAIL_SETTINGS['enabled'] or not EMAIL_SETTINGS['sender_email']:
        return False, "Email not configured"
    
    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_SETTINGS['sender_email']
        msg['To'] = recipient
        msg['Subject'] = subject
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach file if provided
        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, 'rb') as f:
                attach = MIMEApplication(f.read(), _subtype="pdf")
                attach.add_header('Content-Disposition', 'attachment', 
                                filename=os.path.basename(attachment_path))
                msg.attach(attach)
        
        # Send email
        server = smtplib.SMTP(EMAIL_SETTINGS['smtp_server'], EMAIL_SETTINGS['smtp_port'])
        server.starttls()
        server.login(EMAIL_SETTINGS['sender_email'], EMAIL_SETTINGS['sender_password'])
        server.send_message(msg)
        server.quit()
        
        return True, "Email sent successfully"
    except Exception as e:
        return False, f"Email error: {str(e)}"

def export_to_excel(data, headers, filepath):
    """Export data to Excel file"""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Report"
    
    # Add headers
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True)
        cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        cell.font = Font(bold=True, color="FFFFFF")
        cell.alignment = Alignment(horizontal="center")
    
    # Add data
    for row_idx, row_data in enumerate(data, 2):
        for col_idx, value in enumerate(row_data, 1):
            ws.cell(row=row_idx, column=col_idx, value=value)
    
    # Auto-size columns
    for column in ws.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(cell.value)
            except:
                pass
        adjusted_width = min(max_length + 2, 50)
        ws.column_dimensions[column_letter].width = adjusted_width
    
    wb.save(filepath)
    return filepath

# ----------------- SIMPLE TOAST -----------------
def toast(root, text, bg=ACCENT, duration=1800):
    """Tiny non-blocking notification using Toplevel."""
    t = tk.Toplevel(root)
    t.overrideredirect(True)
    t.config(bg=bg)
    # position near top-right of main window
    x = root.winfo_rootx() + 20
    y = root.winfo_rooty() + 20
    t.geometry(f"+{x}+{y}")
    lbl = tk.Label(t, text=text, bg=bg, fg="white", font=("Segoe UI", 10, "bold"), padx=10, pady=5)
    lbl.pack()
    t.after(duration, t.destroy)

# ----------------- DATABASE -----------------
class DB:
    def __init__(self, path=DB_FILE):
        self.conn = sqlite3.connect(path, check_same_thread=False)
        self.cursor = self.conn.cursor()
        self.init_schema()

    def init_schema(self):
        # USERS: username (pk), password_hash, full_name, role (admin/user), email
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                username TEXT PRIMARY KEY,
                password_hash TEXT,
                full_name TEXT,
                role TEXT DEFAULT 'user',
                email TEXT
            )
        """)
        # VEHICLES: id, number, type, user (who parked), slot_id (nullable), entry_time, exit_time
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS vehicles (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                number TEXT,
                type TEXT,
                user TEXT,
                slot_id INTEGER,
                entry_time TEXT,
                exit_time TEXT
            )
        """)
        # SLOTS: id, name, type_allowed (Car/Motor/Both), status (free/occupied), hourly_rate
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS slots (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT UNIQUE,
                type_allowed TEXT,
                status TEXT DEFAULT 'free',
                hourly_rate REAL DEFAULT 0
            )
        """)
        # PAYMENTS: id, vehicle_number, amount, paid_at, duration_hours, generated_by, receipt_path, payment_method
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS payments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                vehicle_number TEXT,
                amount REAL,
                paid_at TEXT,
                duration_hours REAL,
                generated_by TEXT,
                receipt_path TEXT,
                payment_method TEXT DEFAULT 'cash'
            )
        """)
        # SETTINGS: key-value store for system configuration
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        """)
        self.conn.commit()
        # Migrate existing tables (add missing columns if they don't exist)
        self._migrate_schema()
        # ensure admin exists
        self.ensure_admin()

    def _migrate_schema(self):
        """Add missing columns to existing tables for backward compatibility"""
        try:
            # Check and add email column to users
            self.cursor.execute("PRAGMA table_info(users)")
            cols = [col[1] for col in self.cursor.fetchall()]
            if 'email' not in cols:
                self.cursor.execute("ALTER TABLE users ADD COLUMN email TEXT")
            
            # Check and add hourly_rate to slots
            self.cursor.execute("PRAGMA table_info(slots)")
            cols = [col[1] for col in self.cursor.fetchall()]
            if 'hourly_rate' not in cols:
                self.cursor.execute("ALTER TABLE slots ADD COLUMN hourly_rate REAL DEFAULT 0")
            
            # Check and add payment_method to payments
            self.cursor.execute("PRAGMA table_info(payments)")
            cols = [col[1] for col in self.cursor.fetchall()]
            if 'payment_method' not in cols:
                self.cursor.execute("ALTER TABLE payments ADD COLUMN payment_method TEXT DEFAULT 'cash'")
            
            self.conn.commit()
        except Exception as e:
            print(f"Migration warning: {e}")

    def ensure_admin(self):
        self.cursor.execute("SELECT * FROM users WHERE username='admin'")
        if not self.cursor.fetchone():
            admin_pw = hash_password("admin123")  # default, tell user to change
            self.cursor.execute("INSERT INTO users(username,password_hash,full_name,role) VALUES(?,?,?,?)",
                                ("admin", admin_pw, "Administrator", "admin"))
            self.conn.commit()

    # --- users CRUD ---
    def create_user(self, username, password, full_name, role="user", email=""):
        pw_hash = hash_password(password)
        self.cursor.execute("INSERT INTO users(username,password_hash,full_name,role,email) VALUES(?,?,?,?,?)",
                            (username, pw_hash, full_name, role, email))
        self.conn.commit()

    def get_user(self, username):
        self.cursor.execute("SELECT username,full_name,role,email FROM users WHERE username=?", (username,))
        return self.cursor.fetchone()

    def validate_user(self, username, password):
        self.cursor.execute("SELECT password_hash FROM users WHERE username=?", (username,))
        row = self.cursor.fetchone()
        if not row:
            return False
        return row[0] == hash_password(password)

    def update_password(self, username, new_password):
        self.cursor.execute("UPDATE users SET password_hash=? WHERE username=?", (hash_password(new_password), username))
        self.conn.commit()

    def update_user(self, username, full_name=None, email=None, role=None):
        """Update user details"""
        parts = []
        vals = []
        if full_name is not None:
            parts.append("full_name=?"); vals.append(full_name)
        if email is not None:
            parts.append("email=?"); vals.append(email)
        if role is not None:
            parts.append("role=?"); vals.append(role)
        if parts:
            vals.append(username)
            self.cursor.execute(f"UPDATE users SET {', '.join(parts)} WHERE username=?", vals)
            self.conn.commit()

    def delete_user(self, username):
        self.cursor.execute("DELETE FROM users WHERE username=?", (username,))
        self.conn.commit()

    def list_users(self):
        self.cursor.execute("SELECT username, full_name, role, email FROM users")
        return self.cursor.fetchall()

    # --- slots CRUD ---
    def create_slot(self, name, type_allowed, hourly_rate=0):
        self.cursor.execute("INSERT INTO slots(name,type_allowed,status,hourly_rate) VALUES(?,?,?,?)", 
                          (name, type_allowed, "free", hourly_rate))
        self.conn.commit()

    def update_slot(self, slot_id, name=None, type_allowed=None, status=None, hourly_rate=None):
        parts = []
        vals = []
        if name is not None:
            parts.append("name=?"); vals.append(name)
        if type_allowed is not None:
            parts.append("type_allowed=?"); vals.append(type_allowed)
        if status is not None:
            parts.append("status=?"); vals.append(status)
        if hourly_rate is not None:
            parts.append("hourly_rate=?"); vals.append(hourly_rate)
        vals.append(slot_id)
        self.cursor.execute(f"UPDATE slots SET {', '.join(parts)} WHERE id=?", vals)
        self.conn.commit()

    def delete_slot(self, slot_id):
        self.cursor.execute("DELETE FROM slots WHERE id=?", (slot_id,))
        self.conn.commit()

    def list_slots(self):
        self.cursor.execute("SELECT id,name,type_allowed,status,hourly_rate FROM slots")
        return self.cursor.fetchall()
    
    def get_slot_by_id(self, slot_id):
        self.cursor.execute("SELECT id,name,type_allowed,status,hourly_rate FROM slots WHERE id=?", (slot_id,))
        return self.cursor.fetchone()

    def get_free_slot_for_type(self, vtype):
        # try exact type then 'Both'
        self.cursor.execute("SELECT id,name,hourly_rate FROM slots WHERE status='free' AND (type_allowed=? OR type_allowed='Both') LIMIT 1", (vtype,))
        return self.cursor.fetchone()

    # --- vehicles CRUD ---
    def park_vehicle(self, number, vtype, username, slot_id, entry_time):
        self.cursor.execute("""
            INSERT INTO vehicles(number,type,user,slot_id,entry_time,exit_time)
            VALUES(?,?,?,?,?,NULL)
        """, (number, vtype, username, slot_id, entry_time))
        self.cursor.execute("UPDATE slots SET status='occupied' WHERE id=?", (slot_id,))
        self.conn.commit()

    def exit_vehicle(self, number, exit_time):
        # update latest vehicle with this number that has null exit_time
        self.cursor.execute("""
            UPDATE vehicles SET exit_time=?
            WHERE number=? AND exit_time IS NULL
        """, (exit_time, number))
        # free slot(s)
        self.cursor.execute("SELECT slot_id FROM vehicles WHERE number=? ORDER BY id DESC LIMIT 1", (number,))
        r = self.cursor.fetchone()
        if r and r[0]:
            self.cursor.execute("UPDATE slots SET status='free' WHERE id=?", (r[0],))
        self.conn.commit()
        return self.cursor.rowcount

    def list_parked(self):
        self.cursor.execute("SELECT id,number,type,user,slot_id,entry_time,exit_time FROM vehicles ORDER BY id DESC")
        return self.cursor.fetchall()

    def search_vehicles(self, search_term="", date_from="", date_to=""):
        """Search vehicles by number, user, or date range"""
        query = "SELECT id,number,type,user,slot_id,entry_time,exit_time FROM vehicles WHERE 1=1"
        params = []
        
        if search_term:
            query += " AND (number LIKE ? OR user LIKE ?)"
            params.extend([f"%{search_term}%", f"%{search_term}%"])
        
        if date_from:
            query += " AND entry_time >= ?"
            params.append(date_from)
        
        if date_to:
            query += " AND entry_time <= ?"
            params.append(date_to)
        
        query += " ORDER BY id DESC"
        self.cursor.execute(query, params)
        return self.cursor.fetchall()

    def get_last_vehicle_record(self, number):
        self.cursor.execute("SELECT id,number,type,user,slot_id,entry_time,exit_time FROM vehicles WHERE number=? ORDER BY id DESC LIMIT 1", (number,))
        return self.cursor.fetchone()

    # --- payments ---
    def record_payment(self, vehicle_number, amount, duration_hours, generated_by, receipt_path, payment_method="cash"):
        paid_at = now_str()
        self.cursor.execute("INSERT INTO payments(vehicle_number,amount,paid_at,duration_hours,generated_by,receipt_path,payment_method) VALUES(?,?,?,?,?,?,?)",
                            (vehicle_number, amount, paid_at, duration_hours, generated_by, receipt_path, payment_method))
        self.conn.commit()

    def list_payments(self):
        self.cursor.execute("SELECT id,vehicle_number,amount,paid_at,duration_hours,generated_by,receipt_path,payment_method FROM payments ORDER BY id DESC")
        return self.cursor.fetchall()
    
    def search_payments(self, search_term="", date_from="", date_to=""):
        """Search payments by vehicle number or date range"""
        query = "SELECT id,vehicle_number,amount,paid_at,duration_hours,generated_by,receipt_path,payment_method FROM payments WHERE 1=1"
        params = []
        
        if search_term:
            query += " AND (vehicle_number LIKE ? OR generated_by LIKE ?)"
            params.extend([f"%{search_term}%", f"%{search_term}%"])
        
        if date_from:
            query += " AND paid_at >= ?"
            params.append(date_from)
        
        if date_to:
            query += " AND paid_at <= ?"
            params.append(date_to)
        
        query += " ORDER BY id DESC"
        self.cursor.execute(query, params)
        return self.cursor.fetchall()
    
    def get_revenue_stats(self, date_from="", date_to=""):
        """Get revenue statistics for a date range"""
        query = "SELECT SUM(amount) as total, COUNT(*) as count FROM payments WHERE 1=1"
        params = []
        
        if date_from:
            query += " AND paid_at >= ?"
            params.append(date_from)
        
        if date_to:
            query += " AND paid_at <= ?"
            params.append(date_to)
        
        self.cursor.execute(query, params)
        result = self.cursor.fetchone()
        return {'total': result[0] or 0, 'count': result[1] or 0}
    
    def get_daily_revenue(self, days=7):
        """Get daily revenue for the last N days"""
        self.cursor.execute("""
            SELECT DATE(paid_at) as date, SUM(amount) as revenue
            FROM payments
            WHERE paid_at >= datetime('now', '-' || ? || ' days')
            GROUP BY DATE(paid_at)
            ORDER BY date
        """, (days,))
        return self.cursor.fetchall()
    
    def get_occupancy_stats(self):
        """Get current slot occupancy statistics"""
        self.cursor.execute("SELECT status, COUNT(*) FROM slots GROUP BY status")
        stats = dict(self.cursor.fetchall())
        return {
            'occupied': stats.get('occupied', 0),
            'free': stats.get('free', 0),
            'total': sum(stats.values())
        }
    
    # --- settings CRUD ---
    def get_setting(self, key, default=None):
        self.cursor.execute("SELECT value FROM settings WHERE key=?", (key,))
        row = self.cursor.fetchone()
        return row[0] if row else default
    
    def set_setting(self, key, value):
        self.cursor.execute("INSERT OR REPLACE INTO settings(key, value) VALUES(?,?)", (key, value))
        self.conn.commit()
    
    def get_all_settings(self):
        self.cursor.execute("SELECT key, value FROM settings")
        return dict(self.cursor.fetchall())

# ----------------- APPLICATION -----------------
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title(APP_TITLE)
        self.geometry(WINDOW_SIZE)
        self.configure(bg=BG)
        self.db = DB()
        self.current_user = None  # username
        self.current_user_role = None  # user role (admin/user)
        self.create_widgets()

    def create_widgets(self):
        # top menu (simple)
        menubar = tk.Menu(self)
        self.config(menu=menubar)
        account_menu = tk.Menu(menubar, tearoff=0)
        account_menu.add_command(label="Profile", command=self.show_profile)
        account_menu.add_separator()
        account_menu.add_command(label="Exit", command=self.quit)
        menubar.add_cascade(label="Account", menu=account_menu)

        help_menu = tk.Menu(menubar, tearoff=0)
        help_menu.add_command(label="About", command=self.show_about)
        menubar.add_cascade(label="Help", menu=help_menu)

        # main container
        self.container = tk.Frame(self, bg=BG)
        self.container.pack(fill="both", expand=True)

        # create frames/pages dict
        self.pages = {}
        for Page in (LoginPage, RegisterPage, DashboardPage, UserDashboardPage, AdminManagePage, SlotMgmtPage, 
                     VehiclesPage, PaymentsPage, ProfilePage, SettingsPage, ReportsPage):
            page = Page(self.container, self)
            page.grid(row=0, column=0, sticky="nsew")
            self.pages[Page.__name__] = page

        # start with login
        self.show_page("LoginPage")

    def show_page(self, name):
        page = self.pages[name]
        page.tkraise()
        if hasattr(page, "refresh"):
            page.refresh()

    def show_about(self):
        messagebox.showinfo("About", "Smart Parking System\nUpgraded for UTAMU project.\nAuthor: Student\nFeatures: SQLite, hashed passwords, slots, payments, receipts.")

    def show_profile(self):
        if not self.current_user:
            toast(self, "Login first!", bg=ERROR)
            return
        self.show_page("ProfilePage")

# ----------------- PAGES -----------------
class Page(tk.Frame):
    def __init__(self, parent, app: App):
        super().__init__(parent, bg=BG)
        self.app = app

# ---------- LOGIN PAGE ----------
class LoginPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        card = tk.Frame(self, bg=CARD, padx=20, pady=20)
        card.place(relx=0.5, rely=0.45, anchor="center")

        tk.Label(card, text="Login", font=("Segoe UI", 20, "bold"), bg=CARD, fg=ACCENT).pack(pady=(0,10))
        tk.Label(card, text="Username", bg=CARD).pack(anchor="w")
        self.username = tk.Entry(card, width=30)
        self.username.pack(pady=5)
        tk.Label(card, text="Password", bg=CARD).pack(anchor="w")
        self.password = tk.Entry(card, show="*", width=30)
        self.password.pack(pady=5)

        tk.Button(card, text="Login", width=25, bg=ACCENT, fg="white", command=self.do_login).pack(pady=8)
        tk.Button(card, text="Create account", width=25, bg="#10b981", fg="white", command=lambda: self.app.show_page("RegisterPage")).pack()

        # presentation tip
        tk.Label(card, text="(default admin/admin123)", bg=CARD, fg="gray", font=("Segoe UI", 9)).pack(pady=(10,0))

    def do_login(self):
        u = self.username.get().strip()
        p = self.password.get().strip()
        if not u or not p:
            toast(self.app, "Enter username & password", bg=ERROR)
            return
        if self.app.db.validate_user(u, p):
            self.app.current_user = u
            # Get user role
            user_data = self.app.db.get_user(u)
            if user_data:
                self.app.current_user_role = user_data[2]  # role is 3rd column
            toast(self.app, f"Welcome {u}", bg=SUCCESS)
            # Redirect based on role
            if self.app.current_user_role == "admin":
                self.app.show_page("DashboardPage")  # Admin dashboard
            else:
                self.app.show_page("UserDashboardPage")  # User dashboard
        else:
            toast(self.app, "Invalid credentials", bg=ERROR)

# ---------- REGISTER PAGE ----------
class RegisterPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        card = tk.Frame(self, bg=CARD, padx=20, pady=20)
        card.place(relx=0.5, rely=0.45, anchor="center")
        tk.Label(card, text="Register", font=("Segoe UI", 20, "bold"), bg=CARD, fg=ACCENT).pack(pady=(0,10))
        tk.Label(card, text="Full name", bg=CARD).pack(anchor="w")
        self.fullname = tk.Entry(card, width=30); self.fullname.pack(pady=5)
        tk.Label(card, text="Username", bg=CARD).pack(anchor="w")
        self.username = tk.Entry(card, width=30); self.username.pack(pady=5)
        tk.Label(card, text="Password", bg=CARD).pack(anchor="w")
        self.password = tk.Entry(card, show="*", width=30); self.password.pack(pady=5)
        tk.Button(card, text="Register", width=25, bg="#10b981", fg="white", command=self.do_register).pack(pady=8)
        tk.Button(card, text="Back to Login", width=25, bg=ACCENT, fg="white", command=lambda: self.app.show_page("LoginPage")).pack()

    def do_register(self):
        name = self.fullname.get().strip()
        u = self.username.get().strip()
        p = self.password.get().strip()
        if not name or not u or not p:
            toast(self.app, "Fill all fields", bg=ERROR); return
        try:
            self.app.db.create_user(u, p, name, role="user")
            toast(self.app, "Registered! Please login", bg=SUCCESS)
            self.app.show_page("LoginPage")
        except sqlite3.IntegrityError:
            toast(self.app, "Username already exists", bg=ERROR)

# ---------- USER DASHBOARD ----------
class UserDashboardPage(Page):
    """Simplified dashboard for regular users"""
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", padx=20, pady=10)
        self.welcome_lbl = tk.Label(top, text="Welcome", bg=BG, font=("Segoe UI", 16, "bold"), fg=ACCENT)
        self.welcome_lbl.pack(side="left")
        
        # User actions - limited features
        actions = tk.Frame(top, bg=BG)
        actions.pack(side="right")
        tk.Button(actions, text="Park Vehicle", command=self.quick_park, bg=SUCCESS, fg="white", font=("Segoe UI", 10, "bold")).pack(side="left", padx=5)
        tk.Button(actions, text="My Vehicles", command=lambda: self.app.show_page("VehiclesPage"), bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(actions, text="My Payments", command=lambda: self.app.show_page("PaymentsPage"), bg=ACCENT, fg="white").pack(side="left", padx=5)

        # Main content
        main_content = tk.Frame(self, bg=BG)
        main_content.pack(fill="both", expand=True, padx=20, pady=20)
        
        # Info card
        info_card = tk.Frame(main_content, bg=CARD, padx=30, pady=30)
        info_card.pack(fill="both", expand=True)
        
        tk.Label(info_card, text="Quick Park Your Vehicle", bg=CARD, font=("Segoe UI", 18, "bold"), fg=ACCENT).pack(pady=(0, 20))
        tk.Label(info_card, text="Click the button below to park your vehicle quickly", bg=CARD, font=("Segoe UI", 11)).pack(pady=5)
        
        tk.Button(info_card, text="🚗 Quick Park Now", command=self.quick_park, 
                 bg=SUCCESS, fg="white", font=("Segoe UI", 14, "bold"), padx=30, pady=15).pack(pady=20)
        
        # Divider
        tk.Frame(info_card, bg="#e5e7eb", height=2).pack(fill="x", pady=20)
        
        # User info section
        user_info_frame = tk.Frame(info_card, bg=CARD)
        user_info_frame.pack(fill="x")
        
        # My Active Vehicles
        left_col = tk.Frame(user_info_frame, bg=CARD)
        left_col.pack(side="left", fill="both", expand=True, padx=10)
        
        tk.Label(left_col, text="My Active Vehicles", bg=CARD, font=("Segoe UI", 12, "bold"), fg=ACCENT).pack(anchor="w", pady=(0, 10))
        
        # Tree for user's active vehicles
        cols = ("number", "type", "entry_time", "slot")
        self.tree = ttk.Treeview(left_col, columns=cols, show="headings", height=8)
        self.tree.heading("number", text="Vehicle Number")
        self.tree.heading("type", text="Type")
        self.tree.heading("entry_time", text="Entry Time")
        self.tree.heading("slot", text="Slot")
        self.tree.column("number", width=120, anchor="center")
        self.tree.column("type", width=80, anchor="center")
        self.tree.column("entry_time", width=130, anchor="center")
        self.tree.column("slot", width=60, anchor="center")
        self.tree.pack(fill="both", expand=True)
        
        # Right column - Recent payments
        right_col = tk.Frame(user_info_frame, bg=CARD)
        right_col.pack(side="right", fill="both", expand=True, padx=10)
        
        tk.Label(right_col, text="Recent Payments", bg=CARD, font=("Segoe UI", 12, "bold"), fg=ACCENT).pack(anchor="w", pady=(0, 10))
        
        # Payment summary
        self.payment_frame = tk.Frame(right_col, bg=CARD)
        self.payment_frame.pack(fill="both", expand=True)
        
        self.lbl_total_paid = tk.Label(self.payment_frame, text="Total Paid: 0 UGX", 
                                       bg=CARD, font=("Segoe UI", 11), fg=TEXT)
        self.lbl_total_paid.pack(anchor="w", pady=5)
        
        self.lbl_last_payment = tk.Label(self.payment_frame, text="Last Payment: N/A", 
                                         bg=CARD, font=("Segoe UI", 11), fg=TEXT)
        self.lbl_last_payment.pack(anchor="w", pady=5)
        
        # Action buttons at bottom
        btn_frame = tk.Frame(info_card, bg=CARD)
        btn_frame.pack(fill="x", pady=(20, 0))
        
        tk.Button(btn_frame, text="Exit Vehicle", command=self.exit_vehicle_prompt, 
                 bg=ERROR, fg="white", width=20).pack(side="left", padx=5)
        tk.Button(btn_frame, text="Generate Receipt", command=self.generate_receipt_prompt, 
                 bg=ACCENT, fg="white", width=20).pack(side="left", padx=5)
        tk.Button(btn_frame, text="Refresh", command=self.refresh, 
                 bg="#6b7280", fg="white", width=20).pack(side="right", padx=5)
    
    def refresh(self):
        if not self.app.current_user:
            self.app.show_page("LoginPage")
            return
        
        u = self.app.current_user
        self.welcome_lbl.config(text=f"Welcome, {u}")
        
        # Get user's active vehicles
        all_vehicles = self.app.db.list_parked()
        user_vehicles = [v for v in all_vehicles if v[3] == u and v[6] is None]  # user's active vehicles
        
        # Clear and populate tree
        for r in self.tree.get_children():
            self.tree.delete(r)
        
        for v in user_vehicles:
            self.tree.insert("", "end", values=(v[1], v[2], v[5][:16], v[4]))
        
        # Get user's payment summary
        all_payments = self.app.db.list_payments()
        user_payments = [p for p in all_payments if p[5] == u]  # payments generated by this user
        
        if user_payments:
            total_paid = sum(p[2] for p in user_payments)
            last_payment = user_payments[0][2] if user_payments else 0
            last_date = user_payments[0][3][:16] if user_payments else "N/A"
            
            self.lbl_total_paid.config(text=f"Total Paid: {total_paid:.2f} {CURRENCY}")
            self.lbl_last_payment.config(text=f"Last Payment: {last_payment:.2f} {CURRENCY} on {last_date}")
        else:
            self.lbl_total_paid.config(text="Total Paid: 0 UGX")
            self.lbl_last_payment.config(text="Last Payment: N/A")
    
    def quick_park(self):
        number = simpledialog.askstring("Vehicle Number", "Enter vehicle number:")
        vtype = simpledialog.askstring("Vehicle Type", "Car or Motorcycle:")
        if not number or not vtype:
            toast(self.app, "Cancelled", bg=ERROR)
            return
        
        # Find free slot
        slot = self.app.db.get_free_slot_for_type(vtype)
        if not slot:
            toast(self.app, "No free slot available for this vehicle type", bg=ERROR)
            return
        
        slot_id = slot[0]
        entry_time = now_str()
        user = self.app.current_user or "unknown"
        self.app.db.park_vehicle(number, vtype, user, slot_id, entry_time)
        toast(self.app, f"Parked {number} at slot {slot[1]}", bg=SUCCESS)
        self.refresh()
    
    def exit_vehicle_prompt(self):
        sel = self.tree.selection()
        if not sel:
            toast(self.app, "Select a vehicle from your active vehicles", bg=ERROR)
            return
        
        v = self.tree.item(sel[0])["values"]
        number = v[0]
        
        if messagebox.askyesno("Exit Vehicle", f"Exit vehicle {number}?"):
            exit_time = now_str()
            count = self.app.db.exit_vehicle(number, exit_time)
            if count == 0:
                toast(self.app, "No active record to exit", bg=ERROR)
            else:
                toast(self.app, f"{number} exited at {exit_time}", bg=SUCCESS)
                # Prompt to generate receipt
                if messagebox.askyesno("Generate Receipt", "Would you like to generate a receipt now?"):
                    self.generate_receipt_for(number)
            self.refresh()
    
    def generate_receipt_prompt(self):
        number = simpledialog.askstring("Receipt", "Enter vehicle number:")
        if not number:
            return
        self.generate_receipt_for(number)
    
    def generate_receipt_for(self, number):
        # Call the payment page's receipt generation method
        pp = self.app.pages["PaymentsPage"]
        pp.generate_receipt_for(number)
        self.refresh()

# ---------- ADMIN DASHBOARD ----------
class DashboardPage(Page):
    """Admin-only dashboard with full statistics and analytics"""
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", padx=20, pady=10)
        self.welcome_lbl = tk.Label(top, text="Admin Dashboard", bg=BG, font=("Segoe UI", 16, "bold"), fg=ACCENT)
        self.welcome_lbl.pack(side="left")
        # quick actions - all admin features
        self.actions = tk.Frame(top, bg=BG)
        self.actions.pack(side="right")
        tk.Button(self.actions, text="Slots", command=lambda: self.app.show_page("SlotMgmtPage"), bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(self.actions, text="Vehicles", command=lambda: self.app.show_page("VehiclesPage"), bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(self.actions, text="Payments", command=lambda: self.app.show_page("PaymentsPage"), bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(self.actions, text="Reports", command=lambda: self.app.show_page("ReportsPage"), bg="#10b981", fg="white").pack(side="left", padx=5)
        tk.Button(self.actions, text="Settings", command=lambda: self.app.show_page("SettingsPage"), bg="#f59e0b", fg="white").pack(side="left", padx=5)
        tk.Button(self.actions, text="Admin", command=lambda: self.app.show_page("AdminManagePage"), bg="#6b7280", fg="white").pack(side="left", padx=5)

        # Main content area with statistics
        main_content = tk.Frame(self, bg=BG)
        main_content.pack(fill="both", expand=True, padx=20, pady=10)
        
        # Left side: Statistics cards
        left_frame = tk.Frame(main_content, bg=BG)
        left_frame.pack(side="left", fill="both", expand=True)
        
        # Statistics cards
        stats_frame = tk.Frame(left_frame, bg=BG)
        stats_frame.pack(fill="x", pady=(0, 10))
        
        # Revenue card
        revenue_card = tk.Frame(stats_frame, bg=CARD, padx=15, pady=15)
        revenue_card.pack(side="left", padx=5, fill="both", expand=True)
        tk.Label(revenue_card, text="Total Revenue", bg=CARD, font=("Segoe UI", 10)).pack()
        self.lbl_revenue = tk.Label(revenue_card, text="0 UGX", bg=CARD, font=("Segoe UI", 18, "bold"), fg=SUCCESS)
        self.lbl_revenue.pack()
        
        # Occupancy card
        occ_card = tk.Frame(stats_frame, bg=CARD, padx=15, pady=15)
        occ_card.pack(side="left", padx=5, fill="both", expand=True)
        tk.Label(occ_card, text="Occupancy Rate", bg=CARD, font=("Segoe UI", 10)).pack()
        self.lbl_occupancy = tk.Label(occ_card, text="0%", bg=CARD, font=("Segoe UI", 18, "bold"), fg=ACCENT)
        self.lbl_occupancy.pack()
        
        # Active vehicles card
        active_card = tk.Frame(stats_frame, bg=CARD, padx=15, pady=15)
        active_card.pack(side="left", padx=5, fill="both", expand=True)
        tk.Label(active_card, text="Active Vehicles", bg=CARD, font=("Segoe UI", 10)).pack()
        self.lbl_active = tk.Label(active_card, text="0", bg=CARD, font=("Segoe UI", 18, "bold"), fg=ERROR)
        self.lbl_active.pack()
        
        # Chart frame
        chart_frame = tk.Frame(left_frame, bg=CARD, padx=10, pady=10)
        chart_frame.pack(fill="both", expand=True)
        tk.Label(chart_frame, text="Revenue Trend (Last 7 Days)", bg=CARD, font=("Segoe UI", 12, "bold")).pack()
        
        self.chart_canvas_frame = tk.Frame(chart_frame, bg=CARD)
        self.chart_canvas_frame.pack(fill="both", expand=True)

        # quick park button
        tk.Button(left_frame, text="Quick Park (assign best slot)", bg="#10b981", fg="white", command=self.quick_park, font=("Segoe UI", 10, "bold")).pack(pady=10, fill="x")

        # Right side: Recent activity
        right_frame = tk.Frame(main_content, bg=BG, width=400)
        right_frame.pack(side="right", fill="both", padx=(10, 0))
        
        tk.Label(right_frame, text="Recent Parking Activity", bg=BG, font=("Segoe UI", 12, "bold")).pack(anchor="w")
        
        # parked vehicles table
        cols = ("number","type","entry_time")
        self.tree = ttk.Treeview(right_frame, columns=cols, show="headings", height=20)
        self.tree.heading("number", text="Vehicle")
        self.tree.heading("type", text="Type")
        self.tree.heading("entry_time", text="Entry Time")
        self.tree.column("number", width=100, anchor="center")
        self.tree.column("type", width=80, anchor="center")
        self.tree.column("entry_time", width=130, anchor="center")
        self.tree.pack(fill="both", expand=True)

        btns = tk.Frame(right_frame, bg=BG)
        btns.pack(pady=6, fill="x")
        tk.Button(btns, text="Generate Receipt", command=self.generate_receipt_from_selection, bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(btns, text="Refresh", command=self.refresh, bg="#6b7280", fg="white").pack(side="right", padx=5)

    def refresh(self):
        # Admin-only check
        if self.app.current_user_role != "admin":
            toast(self.app, "Admin access required", bg=ERROR)
            self.app.show_page("UserDashboardPage" if self.app.current_user else "LoginPage")
            return
        
        u = self.app.current_user if self.app.current_user else ""
        self.welcome_lbl.config(text=f"Admin Dashboard - Welcome, {u}")
        
        # Get statistics
        occupancy = self.app.db.get_occupancy_stats()
        revenue_stats = self.app.db.get_revenue_stats()
        
        # Update statistics cards
        self.lbl_revenue.config(text=f"{revenue_stats['total']:.2f} {CURRENCY}")
        
        if occupancy['total'] > 0:
            occ_rate = (occupancy['occupied'] / occupancy['total']) * 100
            self.lbl_occupancy.config(text=f"{occ_rate:.1f}%")
        else:
            self.lbl_occupancy.config(text="N/A")
        
        self.lbl_active.config(text=str(occupancy['occupied']))
        
        # Update revenue chart
        self.update_revenue_chart()
        
        # Update recent activity
        parked = self.app.db.list_parked()
        active_vehicles = [v for v in parked if v[6] is None]  # exit_time is None
        
        # clear tree
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in active_vehicles[:20]:  # Show last 20
            self.tree.insert("", "end", values=(row[1], row[2], row[5]))
    
    def update_revenue_chart(self):
        """Update the revenue trend chart"""
        # Clear previous chart
        for widget in self.chart_canvas_frame.winfo_children():
            widget.destroy()
        
        # Get daily revenue data
        daily_data = self.app.db.get_daily_revenue(7)
        
        if not daily_data:
            tk.Label(self.chart_canvas_frame, text="No revenue data available", 
                    bg=CARD, fg="gray").pack(expand=True)
            return
        
        # Create matplotlib figure
        fig = Figure(figsize=(6, 3), dpi=80, facecolor=CARD)
        ax = fig.add_subplot(111)
        
        dates = [d[0] for d in daily_data]
        revenues = [d[1] for d in daily_data]
        
        ax.plot(dates, revenues, marker='o', color=ACCENT, linewidth=2, markersize=6)
        ax.fill_between(dates, revenues, alpha=0.3, color=ACCENT)
        ax.set_xlabel('Date', fontsize=9)
        ax.set_ylabel(f'Revenue ({CURRENCY})', fontsize=9)
        ax.tick_params(axis='x', rotation=45, labelsize=8)
        ax.tick_params(axis='y', labelsize=8)
        ax.grid(True, alpha=0.3)
        ax.set_facecolor(CARD)
        fig.tight_layout()
        
        # Embed in tkinter
        canvas = FigureCanvasTkAgg(fig, master=self.chart_canvas_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill="both", expand=True)

    def quick_park(self):
        # ask for vehicle number & type
        number = simpledialog.askstring("Vehicle Number", "Enter vehicle number:")
        vtype = simpledialog.askstring("Vehicle Type", "Car or Motorcycle:")
        if not number or not vtype:
            toast(self.app, "Cancelled", bg=ERROR); return
        # find free slot
        slot = self.app.db.get_free_slot_for_type(vtype)
        if not slot:
            toast(self.app, "No free slot available for this vehicle type", bg=ERROR); return
        slot_id = slot[0]
        entry_time = now_str()
        user = self.app.current_user or "unknown"
        self.app.db.park_vehicle(number, vtype, user, slot_id, entry_time)
        toast(self.app, f"Parked {number} at slot {slot[1]}", bg=SUCCESS)
        self.refresh()

    def generate_receipt_from_selection(self):
        sel = self.tree.selection()
        if not sel:
            toast(self.app, "Select a record", bg=ERROR); return
        v = self.tree.item(sel[0])["values"]
        number = v[0]  # Updated index for new tree structure
        # call PaymentsPage generate
        pp = self.app.pages["PaymentsPage"]
        pp.generate_receipt_for(number)

# ---------- SLOT MANAGEMENT PAGE ----------
class SlotMgmtPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="Slot Management", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        # slot list
        cols = ("id","name","type_allowed","status","hourly_rate")
        self.tree = ttk.Treeview(self, columns=cols, show="headings", height=18)
        for c in cols:
            self.tree.heading(c, text=c.replace("_", " ").title())
            self.tree.column(c, width=140, anchor="center")
        self.tree.pack(fill="both", expand=True, padx=20, pady=10)
        # controls
        ctrl = tk.Frame(self, bg=BG)
        ctrl.pack(fill="x", padx=20)
        tk.Button(ctrl, text="Add Slot", command=self.add_slot, bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Edit Slot", command=self.edit_slot, bg="#6b7280", fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Delete Slot", command=self.delete_slot, bg=ERROR, fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Refresh", command=self.refresh).pack(side="right", padx=5)

    def refresh(self):
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in self.app.db.list_slots():
            self.tree.insert("", "end", values=row)

    def add_slot(self):
        name = simpledialog.askstring("Slot name", "Enter slot name (e.g. A1):")
        if not name: return
        type_allowed = simpledialog.askstring("Type allowed", "Enter type allowed (Car, Motorcycle, Both):", initialvalue="Both")
        if type_allowed not in ("Car","Motorcycle","Both"):
            toast(self.app, "Invalid type", bg=ERROR); return
        rate = simpledialog.askfloat("Hourly Rate", f"Enter hourly rate ({CURRENCY}):", initialvalue=HOURLY_RATE_CAR)
        if rate is None: rate = 0
        try:
            self.app.db.create_slot(name, type_allowed, rate)
            toast(self.app, "Slot added", bg=SUCCESS)
            self.refresh()
        except sqlite3.IntegrityError:
            toast(self.app, "Slot name exists", bg=ERROR)

    def edit_slot(self):
        sel = self.tree.selection()
        if not sel: toast(self.app, "Select slot", bg=ERROR); return
        row = self.tree.item(sel[0])["values"]
        slot_id = row[0]
        new_name = simpledialog.askstring("New name", "Enter new slot name:", initialvalue=row[1])
        new_type = simpledialog.askstring("Type allowed", "Car, Motorcycle or Both:", initialvalue=row[2])
        if new_type not in ("Car","Motorcycle","Both"):
            toast(self.app, "Invalid type", bg=ERROR); return
        new_rate = simpledialog.askfloat("Hourly Rate", f"Enter hourly rate ({CURRENCY}):", initialvalue=row[4])
        if new_rate is None: new_rate = row[4]
        self.app.db.update_slot(slot_id, name=new_name, type_allowed=new_type, hourly_rate=new_rate)
        toast(self.app, "Slot updated", bg=SUCCESS)
        self.refresh()

    def delete_slot(self):
        sel = self.tree.selection()
        if not sel: toast(self.app, "Select slot", bg=ERROR); return
        row = self.tree.item(sel[0])["values"]
        slot_id = row[0]
        if messagebox.askyesno("Confirm", f"Delete slot {row[1]}?"):
            self.app.db.delete_slot(slot_id)
            toast(self.app, "Deleted", bg=SUCCESS)
            self.refresh()

# ---------- VEHICLES PAGE ----------
class VehiclesPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        top = tk.Frame(self, bg=BG); top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="Vehicles / History", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        
        # Search frame
        search_frame = tk.Frame(self, bg=BG)
        search_frame.pack(fill="x", padx=20, pady=5)
        tk.Label(search_frame, text="Search:", bg=BG).pack(side="left", padx=5)
        self.search_entry = tk.Entry(search_frame, width=30)
        self.search_entry.pack(side="left", padx=5)
        tk.Button(search_frame, text="Search", command=self.search, bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(search_frame, text="Clear", command=self.clear_search, bg="#6b7280", fg="white").pack(side="left", padx=5)
        
        # tree
        cols = ("id","number","type","user","slot_id","entry_time","exit_time")
        self.tree = ttk.Treeview(self, columns=cols, show="headings", height=16)
        for c in cols:
            self.tree.heading(c, text=c)
            self.tree.column(c, width=120, anchor="center")
        self.tree.pack(fill="both", expand=True, padx=20, pady=10)
        ctrl = tk.Frame(self, bg=BG); ctrl.pack(fill="x", padx=20)
        tk.Button(ctrl, text="Exit Vehicle (record exit)", command=self.exit_vehicle).pack(side="left", padx=5)
        tk.Button(ctrl, text="Refresh", command=self.refresh).pack(side="right", padx=5)

    def refresh(self):
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in self.app.db.list_parked():
            self.tree.insert("", "end", values=row)
    
    def search(self):
        search_term = self.search_entry.get().strip()
        for r in self.tree.get_children():
            self.tree.delete(r)
        results = self.app.db.search_vehicles(search_term)
        for row in results:
            self.tree.insert("", "end", values=row)
        toast(self.app, f"Found {len(results)} results", bg=SUCCESS)
    
    def clear_search(self):
        self.search_entry.delete(0, tk.END)
        self.refresh()

    def exit_vehicle(self):
        sel = self.tree.selection()
        if not sel: toast(self.app, "Select vehicle record", bg=ERROR); return
        row = self.tree.item(sel[0])["values"]
        number = row[1]
        exit_time = now_str()
        count = self.app.db.exit_vehicle(number, exit_time)
        if count == 0:
            toast(self.app, "No active record to exit", bg=ERROR)
        else:
            toast(self.app, f"{number} exited at {exit_time}", bg=SUCCESS)
        self.refresh()

# ---------- PAYMENTS / RECEIPTS PAGE ----------
class PaymentsPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        top = tk.Frame(self, bg=BG); top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="Payments / Receipts", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        
        # Search frame
        search_frame = tk.Frame(self, bg=BG)
        search_frame.pack(fill="x", padx=20, pady=5)
        tk.Label(search_frame, text="Search:", bg=BG).pack(side="left", padx=5)
        self.search_entry = tk.Entry(search_frame, width=30)
        self.search_entry.pack(side="left", padx=5)
        tk.Button(search_frame, text="Search", command=self.search, bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(search_frame, text="Clear", command=self.clear_search, bg="#6b7280", fg="white").pack(side="left", padx=5)
        
        # tree
        cols = ("id","vehicle_number","amount","paid_at","duration_hours","payment_method","generated_by")
        self.tree = ttk.Treeview(self, columns=cols, show="headings", height=16)
        for c in cols:
            self.tree.heading(c, text=c.replace("_", " ").title())
            self.tree.column(c, width=120, anchor="center")
        self.tree.pack(fill="both", expand=True, padx=20, pady=10)
        ctrl = tk.Frame(self, bg=BG); ctrl.pack(fill="x", padx=20)
        tk.Button(ctrl, text="Generate Receipt for Vehicle", command=self.prompt_and_generate).pack(side="left", padx=5)
        tk.Button(ctrl, text="Refresh", command=self.refresh).pack(side="right", padx=5)

    def refresh(self):
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in self.app.db.list_payments():
            self.tree.insert("", "end", values=row[:7])  # Exclude receipt path column
    
    def search(self):
        search_term = self.search_entry.get().strip()
        for r in self.tree.get_children():
            self.tree.delete(r)
        results = self.app.db.search_payments(search_term)
        for row in results:
            self.tree.insert("", "end", values=row[:7])
        toast(self.app, f"Found {len(results)} results", bg=SUCCESS)
    
    def clear_search(self):
        self.search_entry.delete(0, tk.END)
        self.refresh()

    def prompt_and_generate(self):
        number = simpledialog.askstring("Receipt", "Enter vehicle number:")
        if not number: return
        self.generate_receipt_for(number)

    def generate_receipt_for(self, number):
        # find latest vehicle record
        v = self.app.db.get_last_vehicle_record(number)
        if not v:
            toast(self.app, "Vehicle not found", bg=ERROR); return
        # if still parked (exit_time is null), ask to exit first
        if not v[6]:  # exit_time is None
            if not messagebox.askyesno("Not exited", f"Vehicle {number} has not exited. Record exit now?"):
                return
            exit_time = now_str()
            self.app.db.exit_vehicle(number, exit_time)
            v = self.app.db.get_last_vehicle_record(number)
        
        # Ask for payment method
        payment_method = simpledialog.askstring("Payment Method", 
                                               "Enter payment method (cash/card/digital):", 
                                               initialvalue="cash")
        if not payment_method:
            payment_method = "cash"
        
        # compute duration and fee
        entry_time = v[5]
        exit_time = v[6]
        duration = hours_between(entry_time, exit_time)
        duration_rounded = math.ceil(duration * 100) / 100.0  # round up to 2 decimals
        
        # Get slot-specific rate if available
        slot_data = self.app.db.get_slot_by_id(v[4]) if v[4] else None
        if slot_data and slot_data[4] > 0:  # slot has custom rate
            rate = slot_data[4]
        else:
            # Use default rates
            rate = HOURLY_RATE_CAR if v[2].lower().startswith("c") else HOURLY_RATE_MOTOR
        
        amount = max(0, duration * rate)
        amount = round(amount, 2)
        
        # Generate PDF receipt
        fname = f"receipt_{v[1]}_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        try:
            generate_pdf_receipt(v, amount, duration_rounded, payment_method, 
                               self.app.current_user, fname)
            
            # record payment
            self.app.db.record_payment(v[1], amount, duration_rounded, self.app.current_user, 
                                      os.path.abspath(fname), payment_method)
            
            # Ask if user wants to send via email
            user_data = self.app.db.get_user(v[3])  # Get vehicle owner's details
            if user_data and len(user_data) > 3 and user_data[3]:  # Has email
                if messagebox.askyesno("Send Email", f"Send receipt to {user_data[3]}?"):
                    success, msg = send_email_with_attachment(
                        user_data[3],
                        "Parking Receipt",
                        f"Dear {user_data[1]},\n\nPlease find your parking receipt attached.\n\n"
                        f"Vehicle: {v[1]}\nAmount: {amount} {CURRENCY}\n\nThank you!",
                        fname
                    )
                    if success:
                        toast(self.app, "Receipt emailed successfully!", bg=SUCCESS)
                    else:
                        toast(self.app, msg, bg=ERROR)
            
            toast(self.app, f"PDF Receipt saved: {fname}", bg=SUCCESS)
            self.refresh()
        except Exception as e:
            toast(self.app, f"Error generating receipt: {str(e)}", bg=ERROR)

# ---------- ADMIN MANAGEMENT PAGE ----------
class AdminManagePage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()
    
    def refresh(self):
        # Check admin access on refresh
        if self.app.current_user_role != "admin":
            toast(self.app, "Admin access required", bg=ERROR)
            self.app.show_page("DashboardPage")
            return
        # Continue with normal refresh
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in self.app.db.list_users():
            self.tree.insert("", "end", values=row)

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="Admin - User Management", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        # Tree
        cols = ("username","full_name","role","email")
        self.tree = ttk.Treeview(self, columns=cols, show="headings", height=18)
        for c in cols:
            self.tree.heading(c, text=c.replace("_", " ").title())
            self.tree.column(c, width=200, anchor="center")
        self.tree.pack(fill="both", expand=True, padx=20, pady=10)
        ctrl = tk.Frame(self, bg=BG); ctrl.pack(fill="x", padx=20)
        tk.Button(ctrl, text="Add User", command=self.add_user, bg=ACCENT, fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Edit User", command=self.edit_user, bg="#10b981", fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Delete User", command=self.delete_user, bg=ERROR, fg="white").pack(side="left", padx=5)
        tk.Button(ctrl, text="Reset Password", command=self.reset_password).pack(side="left", padx=5)
        tk.Button(ctrl, text="Refresh", command=self.refresh).pack(side="right", padx=5)

    def refresh(self):
        for r in self.tree.get_children():
            self.tree.delete(r)
        for row in self.app.db.list_users():
            self.tree.insert("", "end", values=row)

    def add_user(self):
        uname = simpledialog.askstring("Username", "Enter username:")
        if not uname: return
        full = simpledialog.askstring("Full name", "Full name:")
        email = simpledialog.askstring("Email", "Email address (optional):")
        pw = simpledialog.askstring("Password", "Set password:")
        role = simpledialog.askstring("Role", "Role (admin/user):", initialvalue="user")
        if role not in ("admin","user"):
            toast(self.app, "Invalid role", bg=ERROR); return
        try:
            self.app.db.create_user(uname, pw, full, role=role, email=email or "")
            toast(self.app, "User added", bg=SUCCESS)
            self.refresh()
        except sqlite3.IntegrityError:
            toast(self.app, "Username exists", bg=ERROR)
    
    def edit_user(self):
        sel = self.tree.selection()
        if not sel: 
            toast(self.app, "Select user", bg=ERROR)
            return
        row = self.tree.item(sel[0])["values"]
        uname = row[0]
        
        # Get new details
        new_full = simpledialog.askstring("Full name", "Full name:", initialvalue=row[1])
        new_email = simpledialog.askstring("Email", "Email:", initialvalue=row[3] if len(row) > 3 else "")
        new_role = simpledialog.askstring("Role", "Role (admin/user):", initialvalue=row[2])
        
        if new_role not in ("admin","user"):
            toast(self.app, "Invalid role", bg=ERROR)
            return
        
        # Update user
        self.app.db.update_user(uname, full_name=new_full, email=new_email, role=new_role)
        toast(self.app, "User updated", bg=SUCCESS)
        self.refresh()

    def delete_user(self):
        sel = self.tree.selection()
        if not sel: toast(self.app, "Select user", bg=ERROR); return
        uname = self.tree.item(sel[0])["values"][0]
        if uname == self.app.current_user:
            toast(self.app, "Cannot delete logged in user", bg=ERROR); return
        if messagebox.askyesno("Confirm", f"Delete user {uname}?"):
            self.app.db.delete_user(uname)
            toast(self.app, "Deleted", bg=SUCCESS)
            self.refresh()

    def reset_password(self):
        sel = self.tree.selection()
        if not sel: toast(self.app, "Select user", bg=ERROR); return
        uname = self.tree.item(sel[0])["values"][0]
        self.app.db.update_password(uname, "user123")
        toast(self.app, f"Password reset to 'user123' for {uname}", bg=SUCCESS)

# ---------- PROFILE PAGE ----------
class ProfilePage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()

    def build(self):
        card = tk.Frame(self, bg=CARD, padx=20, pady=20)
        card.place(relx=0.5, rely=0.45, anchor="center")
        tk.Label(card, text="Profile", font=("Segoe UI", 18, "bold"), bg=CARD, fg=ACCENT).pack(pady=10)
        tk.Label(card, text="Username:", bg=CARD).pack(anchor="w")
        self.lbl_user = tk.Label(card, text="", bg=CARD, font=("Segoe UI", 12, "bold"))
        self.lbl_user.pack(anchor="w", pady=(0,6))
        tk.Label(card, text="Full name:", bg=CARD).pack(anchor="w")
        self.fullname = tk.Entry(card, width=30); self.fullname.pack(pady=6)
        tk.Label(card, text="Email:", bg=CARD).pack(anchor="w")
        self.email = tk.Entry(card, width=30); self.email.pack(pady=6)
        tk.Label(card, text="New Password (leave blank to keep current):", bg=CARD).pack(anchor="w")
        self.newpw = tk.Entry(card, show="*", width=30); self.newpw.pack(pady=6)
        tk.Button(card, text="Save Profile", bg=ACCENT, fg="white", command=self.save_profile).pack(pady=8)
        tk.Button(card, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack()

    def refresh(self):
        if not self.app.current_user:
            toast(self.app, "Not logged in", bg=ERROR); return
        data = self.app.db.get_user(self.app.current_user)
        if data:
            self.lbl_user.config(text=data[0])
            self.fullname.delete(0, tk.END)
            self.fullname.insert(0, data[1] if data[1] else "")
            self.email.delete(0, tk.END)
            self.email.insert(0, data[3] if len(data) > 3 and data[3] else "")
        else:
            toast(self.app, "User not found", bg=ERROR)

    def save_profile(self):
        new_name = self.fullname.get().strip()
        new_email = self.email.get().strip()
        new_pw = self.newpw.get().strip()
        # update user details
        if new_name or new_email:
            self.app.db.update_user(self.app.current_user, full_name=new_name, email=new_email)
        if new_pw:
            self.app.db.update_password(self.app.current_user, new_pw)
        toast(self.app, "Profile updated", bg=SUCCESS)
        self.app.show_page("DashboardPage")

# ---------- SETTINGS PAGE ----------
class SettingsPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()
    
    def _check_admin(self):
        """Check if user has admin access"""
        if self.app.current_user_role != "admin":
            toast(self.app, "Admin access required", bg=ERROR)
            self.app.show_page("DashboardPage")
            return False
        return True

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="System Settings", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        
        # Settings form in a card
        card = tk.Frame(self, bg=CARD, padx=30, pady=30)
        card.place(relx=0.5, rely=0.5, anchor="center")
        
        tk.Label(card, text="Default Rates", bg=CARD, font=("Segoe UI", 14, "bold"), fg=ACCENT).grid(row=0, column=0, columnspan=2, pady=10, sticky="w")
        
        tk.Label(card, text="Car Hourly Rate (UGX):", bg=CARD).grid(row=1, column=0, sticky="w", pady=5)
        self.car_rate = tk.Entry(card, width=20)
        self.car_rate.grid(row=1, column=1, pady=5, padx=10)
        
        tk.Label(card, text="Motorcycle Hourly Rate (UGX):", bg=CARD).grid(row=2, column=0, sticky="w", pady=5)
        self.motor_rate = tk.Entry(card, width=20)
        self.motor_rate.grid(row=2, column=1, pady=5, padx=10)
        
        tk.Label(card, text="Email Configuration", bg=CARD, font=("Segoe UI", 14, "bold"), fg=ACCENT).grid(row=3, column=0, columnspan=2, pady=(20, 10), sticky="w")
        
        tk.Label(card, text="SMTP Server:", bg=CARD).grid(row=4, column=0, sticky="w", pady=5)
        self.smtp_server = tk.Entry(card, width=20)
        self.smtp_server.grid(row=4, column=1, pady=5, padx=10)
        
        tk.Label(card, text="SMTP Port:", bg=CARD).grid(row=5, column=0, sticky="w", pady=5)
        self.smtp_port = tk.Entry(card, width=20)
        self.smtp_port.grid(row=5, column=1, pady=5, padx=10)
        
        tk.Label(card, text="Sender Email:", bg=CARD).grid(row=6, column=0, sticky="w", pady=5)
        self.sender_email = tk.Entry(card, width=20)
        self.sender_email.grid(row=6, column=1, pady=5, padx=10)
        
        tk.Label(card, text="Sender Password:", bg=CARD).grid(row=7, column=0, sticky="w", pady=5)
        self.sender_password = tk.Entry(card, show="*", width=20)
        self.sender_password.grid(row=7, column=1, pady=5, padx=10)
        
        self.email_enabled = tk.BooleanVar()
        tk.Checkbutton(card, text="Enable Email Notifications", variable=self.email_enabled, bg=CARD).grid(row=8, column=0, columnspan=2, pady=10)
        
        btn_frame = tk.Frame(card, bg=CARD)
        btn_frame.grid(row=9, column=0, columnspan=2, pady=20)
        tk.Button(btn_frame, text="Save Settings", bg=ACCENT, fg="white", command=self.save_settings, width=15).pack(side="left", padx=5)
        tk.Button(btn_frame, text="Test Email", bg="#10b981", fg="white", command=self.test_email, width=15).pack(side="left", padx=5)
    
    def refresh(self):
        # Check admin access
        if not self._check_admin():
            return
        
        # Load settings from database
        settings = self.app.db.get_all_settings()
        
        self.car_rate.delete(0, tk.END)
        self.car_rate.insert(0, settings.get('car_rate', str(HOURLY_RATE_CAR)))
        
        self.motor_rate.delete(0, tk.END)
        self.motor_rate.insert(0, settings.get('motor_rate', str(HOURLY_RATE_MOTOR)))
        
        self.smtp_server.delete(0, tk.END)
        self.smtp_server.insert(0, settings.get('smtp_server', EMAIL_SETTINGS['smtp_server']))
        
        self.smtp_port.delete(0, tk.END)
        self.smtp_port.insert(0, settings.get('smtp_port', str(EMAIL_SETTINGS['smtp_port'])))
        
        self.sender_email.delete(0, tk.END)
        self.sender_email.insert(0, settings.get('sender_email', ''))
        
        self.sender_password.delete(0, tk.END)
        self.sender_password.insert(0, settings.get('sender_password', ''))
        
        self.email_enabled.set(settings.get('email_enabled', 'False') == 'True')
    
    def save_settings(self):
        global HOURLY_RATE_CAR, HOURLY_RATE_MOTOR
        
        try:
            # Save rates
            car_rate = float(self.car_rate.get())
            motor_rate = float(self.motor_rate.get())
            
            self.app.db.set_setting('car_rate', str(car_rate))
            self.app.db.set_setting('motor_rate', str(motor_rate))
            
            # Update global variables
            HOURLY_RATE_CAR = car_rate
            HOURLY_RATE_MOTOR = motor_rate
            
            # Save email settings
            self.app.db.set_setting('smtp_server', self.smtp_server.get())
            self.app.db.set_setting('smtp_port', self.smtp_port.get())
            self.app.db.set_setting('sender_email', self.sender_email.get())
            self.app.db.set_setting('sender_password', self.sender_password.get())
            self.app.db.set_setting('email_enabled', str(self.email_enabled.get()))
            
            # Update global email settings
            EMAIL_SETTINGS['smtp_server'] = self.smtp_server.get()
            EMAIL_SETTINGS['smtp_port'] = int(self.smtp_port.get())
            EMAIL_SETTINGS['sender_email'] = self.sender_email.get()
            EMAIL_SETTINGS['sender_password'] = self.sender_password.get()
            EMAIL_SETTINGS['enabled'] = self.email_enabled.get()
            
            toast(self.app, "Settings saved successfully!", bg=SUCCESS)
        except ValueError:
            toast(self.app, "Invalid rate values", bg=ERROR)
    
    def test_email(self):
        test_email = simpledialog.askstring("Test Email", "Enter email address to send test:")
        if not test_email:
            return
        
        # Update email settings temporarily
        EMAIL_SETTINGS['smtp_server'] = self.smtp_server.get()
        EMAIL_SETTINGS['smtp_port'] = int(self.smtp_port.get())
        EMAIL_SETTINGS['sender_email'] = self.sender_email.get()
        EMAIL_SETTINGS['sender_password'] = self.sender_password.get()
        EMAIL_SETTINGS['enabled'] = True
        
        success, msg = send_email_with_attachment(
            test_email,
            "Test Email from Smart Parking System",
            "This is a test email. If you received this, your email configuration is working correctly!",
            None
        )
        
        if success:
            toast(self.app, "Test email sent successfully!", bg=SUCCESS)
        else:
            toast(self.app, f"Email test failed: {msg}", bg=ERROR)

# ---------- REPORTS PAGE ----------
class ReportsPage(Page):
    def __init__(self, parent, app):
        super().__init__(parent, app)
        self.build()
    
    def _check_admin(self):
        """Check if user has admin access"""
        if self.app.current_user_role != "admin":
            toast(self.app, "Admin access required", bg=ERROR)
            self.app.show_page("DashboardPage")
            return False
        return True

    def build(self):
        top = tk.Frame(self, bg=BG)
        top.pack(fill="x", pady=10, padx=20)
        tk.Label(top, text="Reports & Analytics", font=("Segoe UI", 16, "bold"), fg=ACCENT, bg=BG).pack(side="left")
        tk.Button(top, text="Back", command=lambda: self.app.show_page("DashboardPage")).pack(side="right")
        
        # Main content
        content = tk.Frame(self, bg=BG)
        content.pack(fill="both", expand=True, padx=20, pady=10)
        
        # Left: Summary cards
        left = tk.Frame(content, bg=BG)
        left.pack(side="left", fill="both", expand=True, padx=(0, 10))
        
        # Summary statistics
        summary_frame = tk.Frame(left, bg=CARD, padx=20, pady=20)
        summary_frame.pack(fill="x", pady=(0, 10))
        
        tk.Label(summary_frame, text="Summary Statistics", bg=CARD, font=("Segoe UI", 14, "bold"), fg=ACCENT).pack(anchor="w")
        
        self.stats_text = tk.Text(summary_frame, height=10, width=50, bg=CARD, relief="flat", font=("Segoe UI", 10))
        self.stats_text.pack(fill="x", pady=10)
        
        # Chart area
        chart_frame = tk.Frame(left, bg=CARD, padx=10, pady=10)
        chart_frame.pack(fill="both", expand=True)
        
        tk.Label(chart_frame, text="Revenue & Occupancy Analysis", bg=CARD, font=("Segoe UI", 12, "bold")).pack()
        
        self.chart_canvas_frame = tk.Frame(chart_frame, bg=CARD)
        self.chart_canvas_frame.pack(fill="both", expand=True)
        
        # Right: Export options
        right = tk.Frame(content, bg=CARD, padx=20, pady=20, width=300)
        right.pack(side="right", fill="y")
        
        tk.Label(right, text="Export Reports", bg=CARD, font=("Segoe UI", 14, "bold"), fg=ACCENT).pack(pady=(0, 20))
        
        tk.Label(right, text="Select Report Type:", bg=CARD).pack(anchor="w", pady=5)
        self.report_type = tk.StringVar(value="revenue")
        tk.Radiobutton(right, text="Revenue Report", variable=self.report_type, value="revenue", bg=CARD).pack(anchor="w")
        tk.Radiobutton(right, text="Vehicle History", variable=self.report_type, value="vehicles", bg=CARD).pack(anchor="w")
        tk.Radiobutton(right, text="Payment Records", variable=self.report_type, value="payments", bg=CARD).pack(anchor="w")
        tk.Radiobutton(right, text="Slot Utilization", variable=self.report_type, value="slots", bg=CARD).pack(anchor="w")
        
        tk.Label(right, text="Date Range (optional):", bg=CARD).pack(anchor="w", pady=(15, 5))
        tk.Label(right, text="From:", bg=CARD, font=("Segoe UI", 9)).pack(anchor="w")
        self.date_from = tk.Entry(right, width=20)
        self.date_from.pack(anchor="w", pady=2)
        self.date_from.insert(0, "YYYY-MM-DD")
        
        tk.Label(right, text="To:", bg=CARD, font=("Segoe UI", 9)).pack(anchor="w", pady=(5, 0))
        self.date_to = tk.Entry(right, width=20)
        self.date_to.pack(anchor="w", pady=2)
        self.date_to.insert(0, "YYYY-MM-DD")
        
        tk.Button(right, text="Export to PDF", bg=ACCENT, fg="white", command=self.export_pdf, width=20).pack(pady=(20, 5))
        tk.Button(right, text="Export to Excel", bg="#10b981", fg="white", command=self.export_excel, width=20).pack(pady=5)
        tk.Button(right, text="Refresh Data", bg="#6b7280", fg="white", command=self.refresh, width=20).pack(pady=5)
    
    def refresh(self):
        # Check admin access
        if not self._check_admin():
            return
        
        # Update statistics
        occupancy = self.app.db.get_occupancy_stats()
        revenue_stats = self.app.db.get_revenue_stats()
        payments = self.app.db.list_payments()
        vehicles = self.app.db.list_parked()
        
        stats_text = f"""
Total Slots: {occupancy['total']}
Occupied Slots: {occupancy['occupied']}
Free Slots: {occupancy['free']}
Occupancy Rate: {(occupancy['occupied']/occupancy['total']*100) if occupancy['total'] > 0 else 0:.1f}%

Total Revenue: {revenue_stats['total']:.2f} {CURRENCY}
Total Payments: {revenue_stats['count']}
Average Payment: {(revenue_stats['total']/revenue_stats['count']) if revenue_stats['count'] > 0 else 0:.2f} {CURRENCY}

Total Vehicle Records: {len(vehicles)}
Active Vehicles: {len([v for v in vehicles if v[6] is None])}
        """
        
        self.stats_text.delete(1.0, tk.END)
        self.stats_text.insert(1.0, stats_text.strip())
        
        # Update charts
        self.update_charts()
    
    def update_charts(self):
        # Clear previous chart
        for widget in self.chart_canvas_frame.winfo_children():
            widget.destroy()
        
        # Get data
        daily_revenue = self.app.db.get_daily_revenue(30)
        occupancy = self.app.db.get_occupancy_stats()
        
        if not daily_revenue:
            tk.Label(self.chart_canvas_frame, text="No data available", bg=CARD, fg="gray").pack(expand=True)
            return
        
        # Create figure with subplots
        fig = Figure(figsize=(8, 6), dpi=80, facecolor=CARD)
        
        # Revenue trend
        ax1 = fig.add_subplot(211)
        dates = [d[0] for d in daily_revenue[-14:]]  # Last 14 days
        revenues = [d[1] for d in daily_revenue[-14:]]
        ax1.plot(dates, revenues, marker='o', color=ACCENT, linewidth=2)
        ax1.fill_between(dates, revenues, alpha=0.3, color=ACCENT)
        ax1.set_title('Revenue Trend (Last 14 Days)', fontsize=10, fontweight='bold')
        ax1.set_ylabel(f'Revenue ({CURRENCY})', fontsize=9)
        ax1.tick_params(axis='x', rotation=45, labelsize=7)
        ax1.grid(True, alpha=0.3)
        ax1.set_facecolor(CARD)
        
        # Occupancy pie chart
        ax2 = fig.add_subplot(212)
        if occupancy['total'] > 0:
            sizes = [occupancy['occupied'], occupancy['free']]
            labels = ['Occupied', 'Free']
            colors = [ERROR, SUCCESS]
            ax2.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90)
            ax2.set_title('Current Slot Occupancy', fontsize=10, fontweight='bold')
        ax2.set_facecolor(CARD)
        
        fig.tight_layout()
        
        # Embed in tkinter
        canvas = FigureCanvasTkAgg(fig, master=self.chart_canvas_frame)
        canvas.draw()
        canvas.get_tk_widget().pack(fill="both", expand=True)
    
    def export_pdf(self):
        report_type = self.report_type.get()
        filename = f"{report_type}_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        try:
            doc = SimpleDocTemplate(filename, pagesize=letter)
            elements = []
            styles = getSampleStyleSheet()
            
            # Title
            title = Paragraph(f"<b>{report_type.upper()} REPORT</b>", styles['Title'])
            elements.append(title)
            elements.append(Spacer(1, 0.3*inch))
            
            # Generated date
            date_para = Paragraph(f"Generated: {now_str()}", styles['Normal'])
            elements.append(date_para)
            elements.append(Spacer(1, 0.2*inch))
            
            # Get data based on report type
            if report_type == "revenue":
                data = [['Date', 'Vehicle', 'Amount', 'Payment Method']]
                for p in self.app.db.list_payments()[:50]:
                    data.append([p[3][:10], p[1], f"{p[2]:.2f}", p[7] if len(p) > 7 else 'N/A'])
            elif report_type == "vehicles":
                data = [['Number', 'Type', 'User', 'Entry', 'Exit']]
                for v in self.app.db.list_parked()[:50]:
                    data.append([v[1], v[2], v[3], v[5][:16], v[6][:16] if v[6] else 'Active'])
            elif report_type == "payments":
                data = [['Vehicle', 'Amount', 'Duration (hrs)', 'Paid At']]
                for p in self.app.db.list_payments()[:50]:
                    data.append([p[1], f"{p[2]:.2f}", f"{p[4]:.2f}", p[3][:16]])
            else:  # slots
                data = [['Name', 'Type', 'Status', 'Rate']]
                for s in self.app.db.list_slots():
                    data.append([s[1], s[2], s[3], f"{s[4]:.2f}"])
            
            # Create table
            table = Table(data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            elements.append(table)
            doc.build(elements)
            
            toast(self.app, f"PDF report saved: {filename}", bg=SUCCESS)
        except Exception as e:
            toast(self.app, f"Error generating PDF: {str(e)}", bg=ERROR)
    
    def export_excel(self):
        report_type = self.report_type.get()
        filename = f"{report_type}_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        try:
            # Get data based on report type
            if report_type == "revenue":
                headers = ['ID', 'Vehicle', 'Amount', 'Paid At', 'Duration (hrs)', 'Generated By', 'Payment Method']
                data = [[p[0], p[1], p[2], p[3], p[4], p[5], p[7] if len(p) > 7 else 'N/A'] for p in self.app.db.list_payments()]
            elif report_type == "vehicles":
                headers = ['ID', 'Number', 'Type', 'User', 'Slot ID', 'Entry Time', 'Exit Time']
                data = list(self.app.db.list_parked())
            elif report_type == "payments":
                headers = ['ID', 'Vehicle', 'Amount', 'Paid At', 'Duration (hrs)', 'Generated By']
                data = [[p[0], p[1], p[2], p[3], p[4], p[5]] for p in self.app.db.list_payments()]
            else:  # slots
                headers = ['ID', 'Name', 'Type Allowed', 'Status', 'Hourly Rate']
                data = list(self.app.db.list_slots())
            
            export_to_excel(data, headers, filename)
            toast(self.app, f"Excel report saved: {filename}", bg=SUCCESS)
        except Exception as e:
            toast(self.app, f"Error generating Excel: {str(e)}", bg=ERROR)

# ----------------- MAIN -----------------
def main():
    global HOURLY_RATE_CAR, HOURLY_RATE_MOTOR, EMAIL_SETTINGS
    
    app = App()
    
    # Load settings from database
    settings = app.db.get_all_settings()
    if settings:
        HOURLY_RATE_CAR = float(settings.get('car_rate', HOURLY_RATE_CAR))
        HOURLY_RATE_MOTOR = float(settings.get('motor_rate', HOURLY_RATE_MOTOR))
        EMAIL_SETTINGS['smtp_server'] = settings.get('smtp_server', EMAIL_SETTINGS['smtp_server'])
        EMAIL_SETTINGS['smtp_port'] = int(settings.get('smtp_port', EMAIL_SETTINGS['smtp_port']))
        EMAIL_SETTINGS['sender_email'] = settings.get('sender_email', '')
        EMAIL_SETTINGS['sender_password'] = settings.get('sender_password', '')
        EMAIL_SETTINGS['enabled'] = settings.get('email_enabled', 'False') == 'True'
    
    # optional: pre-create some slots for demo if none exist
    if len(app.db.list_slots()) == 0:
        try:
            app.db.create_slot("A1","Car", HOURLY_RATE_CAR)
            app.db.create_slot("A2","Car", HOURLY_RATE_CAR)
            app.db.create_slot("B1","Motorcycle", HOURLY_RATE_MOTOR)
            app.db.create_slot("General1","Both", HOURLY_RATE_CAR)
        except:
            pass
    app.mainloop()

if __name__ == "__main__":
    main()
