"""
PDF generation utilities for receipts and reports
"""

import os
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch
from utils.helpers import now_str


CURRENCY = "UGX"


def generate_pdf_receipt(vehicle_data, amount, duration_hours, payment_method, generated_by, filepath):
    """Generate a PDF receipt for a vehicle payment"""
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title = Paragraph("<b>SMART PARKING RECEIPT</b>", styles['Title'])
    elements.append(title)
    elements.append(Spacer(1, 0.3*inch))
    
    # Receipt details
    data = [
        ['Generated:', now_str()],
        ['Vehicle Number:', vehicle_data[1]],
        ['Vehicle Type:', vehicle_data[2]],
        ['Parked By:', vehicle_data[3]],
        ['Entry Time:', vehicle_data[5]],
        ['Exit Time:', vehicle_data[6]],
        ['Duration (hours):', f"{duration_hours:.2f}"],
        ['Amount:', f"{amount:.2f} {CURRENCY}"],
        ['Payment Method:', payment_method.upper()],
        ['Generated By:', generated_by],
    ]
    
    table = Table(data, colWidths=[2*inch, 4*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 0.5*inch))
    
    # Footer
    footer = Paragraph("<i>Thank you for using our parking service!</i>", styles['Normal'])
    elements.append(footer)
    
    doc.build(elements)
    return filepath
